### ISSUE TITLE
Add a Strategy object type

### ISSUE THREAD

**Issue by amortization** [skent259/crapssim#23]
I think that it would make sense for us to have a Strategy base class that could be derived from to create strategies. 

Currently, for strategies that have attributes that need to be stored those attributes are passed to the player and stored as strat_info. These items then have to be passed back from the player to the strategy with a kwargs argument as it isn't always apparent what attributes will need to be passed.

If each players strategy was it's own object, the attributes could all be defined and stored by the Strategy which I think will be easier for end users creating strategies to understand. It would also let us remove unit from player, and just allow each strategy to define it's own __init__ method with the necessary arguments allowing more flexibility. 

It would also let us break up complex strategies into multiple smaller methods within the Strategy for code readability and sustainability. 

How I envision the base class looking is
```
class Strategy(ABC):
    @abstractmethod
    def update_bets(self, player: Player, table: Table):
        pass
```

Then have each strategy subclass from it. For strategies without complex inputs or outputs, it will be as simple as taking what is already defined in the method and adding necessary inputs. For example with passline:

```
class PassLineStrategy(Strategy):
    def __init__(self, bet_amount: typing.SupportsFloat):
        self.bet_amount = bet_amount

    def update_bets(self, player: Player, table: Table):
        if table.point == "Off" and not player.has_bets(PassLine):
            player.place_bet(PassLine(self.bet_amount), table)
```

As you can see, it separates the unit parameter from the player and allows any bet amount to be used for the Strategy. This way if the player wanted to use a strategy where they place $5 dollar pass line bets but $100 come bets they wouldn't be beholden to the player.unit when re-using strategies. 

I think that it would really allow you to simplify strategies that are required to store information. For example hammerlock could look something like (untested and just for illustration):
```
class HammerLock(Strategy):
    def __init__(self, bet_amount, win_mult="345"):
        self.bet_amount = bet_amount
        self.win_mult = win_mult
        self.mode = None

    def update_bets(self, player: Player, table: Table):
        PassLineStrategy(self.bet_amount).update_bets(player, table)
        LayOddsStrategy(self.bet_amount).update_bets(player, table)

        self.update_mode(player, table)
        
        if self.mode == 'place68':
            PlaceStrategy(self.bet_amount, numbers={6, 8}, skip_point=False).update_bets(player, table)
        elif self.mode == 'place_inside':
            PlaceStrategy(self.bet_amount, numbers={5, 6, 8, 9}, skip_point=False).update_bets(player, table)
        elif self.mode == 'takedown':
            self.takedown(player)

    def update_mode(self, player: Player, table: Table):
        if self.mode is None and table.point.status == 'On':
            self.mode = 'place68'
        elif self.mode == 'place68' and not player.has_bets(Place6, Place8):
            self.mode = 'place_inside'
        elif self.mode == 'place_inside' and not player.has_bets(Place5, Place6, Place8, Place9):
            self.mode = 'takedown'
            
    def takedown(self, player):
        for bet_type in (Place5, Place6, Place8, Place9):
            player.remove_if_present(bet_type)
```

We could then add other object related methods to the Strategy if we wanted, for instance we could have a __add__ method that could combine multiple strategies so something like the PassLine(5) and Come(100) described above could be represented as just PassLine(5) + Come(100).

Thoughts on this implementation of strategy?

**Comment by skent259** [comment]
These are all fair points. It seems that with this approach (and a fair bit of coding), we could create something where the strategies are:

- Easier overall for experienced programmers to build because the classes will contain objects and can pull from subclasses
- Easier for all users to collect basic strategies (e.g. `player.strategy = PointOffBet(PassLine, 5) + PointOnBet(Field, 15) + PointOnBet(Hard4, 10)` in your example)
- Harder for a beginning programmer to create a detailed strategy unless perhaps they dig into the documentation and learn a bit about python class creation

Thus, any change like this would have to come with a good set of documentation and potentially some walkthroughs.  

I'd still like to think about it more, but my current position would be to implement something like this for v0.4.0 or later. I'd like to have a released version that has the important changes to bet, table, player, etc that are done/in progress with the current strategy syntax. Separating this change from the others will also highlight that it is a fundamental change in the package structure, which I think is important

**Comment by skent259** [comment]
Added with #29, but possibly some additional work to be done. Closing
