### ISSUE TITLE
What are craps-test.py and run_simulations.py in the Python directory for?

### ISSUE THREAD

**Issue by amortization** [skent259/crapssim#8]
It looks like craps-test.py might just be some pre unit testing smoke tests, so I would think that this could be removed or refactored and moved to the test directory. 

run_simulations.py looks like convenience methods to run simulations without having to set up the tables and players etc. I think that these would be good to have somewhere so maybe they can be refined and moved into crapssim?

**Comment by skent259** [comment]
craps-test.py is exactly as you say.  It can be removed with the new testing

I'm not sure what to do with the helper functions in run_simulations.py.  I'm not sure if they add value to the package or confuse it.  Ideally it would be nice to have a place for specific run methods for certain simulations, but there's so many ways to do it that it might be counterproductive to add to crapssim.  Thoughts?

**Comment by amortization** [comment]
For now I added a Pull Request to dev (#9) to just remove that directory.

**Comment by amortization** [comment]
How about Craps.Rproj? Can that be removed as well?

**Comment by skent259** [comment]
Craps.Rproj can be removed (ideally through the .gitignore file).  It dates back to when this directory contained some R tools for visualization, but it makes more sense for them to be separate. 

I really like the idea of some simulation methods that are consistent and well documented.  Since this is a larger issue, I've added it separately in issue #14
